language: node_js
node_js:
  - '0.10'
git:
  submodules: false
before_script:
  - 'npm install -g bower grunt-cli'
  - 'bower install'
  - 'gem install compass'
after_success:
  - 'git config --global user.email "autodeploy@travis.org"'
  - 'git config --global user.name "Auto Deploy"'
  - 'npm run-script deploy'
